# Array operations & Broadcasting

## phase 1

In [2]:
# creating the practice array 

import numpy as np

arr = np.arange(12)

arr = arr.reshape(3,4)

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# SCALER OPERATIONS 

## Add a number

In [13]:
# scalar operations 

# scaler is a single number 


add= arr + 10

print(add)


# this is called vectorized opperations , 

# numpy adds 10 to every element in the array , 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
