## 1 . Reshaping

In [3]:
# creating a basic array 

import numpy as np

arr = np.array([1,2,3,4,5,6])

print("shape is : ",arr.shape)
print(arr)



shape is :  (6,)
[1 2 3 4 5 6]


In [2]:
# reshaping ( changing the dimensions not the data)

re = arr.reshape(2,3)

print( "after reshape  :") 
print(re)


#remember the rows x cols should equal to the total number of elements 

# possible cases :
#(1,6)
#(6,1)
#(2,3)
#(3,2)

#invalid cases

#(2,8) required 8 elements (not possible according our array example(arr))

after reshape  :
[[1 2 3]
 [4 5 6]]


## 2 . Reshaping with -1 

In [5]:
# -1 is automatically calculated the row or cols

#example

import numpy as np

matrix = np.arange(6)

matrix = matrix.reshape(2,-1)  # rows = 2 , cols = 6/2 = 3
 
print(matrix)

[[0 1 2]
 [3 4 5]]


In [7]:
# Example for automatically creating the rows dimension 

mat = matrix.flatten()

mat = mat.reshape(-1,2)  #rows = 6/2 = 3, cols = 2

print(mat)

[[0 1]
 [2 3]
 [4 5]]


# 3. Row vector vs Column vector

## Row vector

In [12]:
# create a practice array 

import numpy as np

arr = np.arange(1,4)

print(arr)  # it is a 1*3 vector but is shape shows as (3,)


print(arr.shape)  # it creates (3,) this is not same as 1*3 



[1 2 3]
(3,)


In [11]:
# so reshape it to (1,3)

x = arr.reshape(1,3)

print(x.shape)

(1, 3)


## column vector

In [17]:
print(arr) # which is 1d array
print()
# making column vector
y = arr.reshape(3,1)

print("after reshape")

print(y)

print("shape : ", y.shape)

[1 2 3]

after reshape
[[1]
 [2]
 [3]]
shape :  (3, 1)


# 4. flatten() vs ravel()

## flatten()

** flatten()** converts the n dimension array into the 1 dimension array

In [20]:
# practice array 

matrix = np.arange(1,13)

matrix = matrix.reshape(4,3)

print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# let convert the matrix in to 1 d array 

# remember , the flatten creates the copy , it does not effect the original array 

f = matrix.flatten()

print(f)

print()

print("original matrix : ")
print()
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

original matrix : 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# modifying the flatten array f , does not effect the original array 

f[2] = 99 
print(f)

print()

print("original array ")
print()
print(matrix) # original array remains same

[ 1  2 99  4  5  6  7  8  9 10 11 12]

original array 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## ravel()

In [27]:
# ravel() converts an n dimension array to 1 dimension 
# ravel() may returns a view if the array in continuous 

# ravel() may return a copy if the array in non continuous

# changing the ravel() array can effect the original array ( same memory usage)

In [29]:
print(matrix)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# r is the ravel array

r = matrix.ravel()  

print(r)

print("original array : ")
print(matrix)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
original array : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
# changing the ravel array(r) effect the original array

r[2] = 100

print(r)

print("original array : ")

print()
print(matrix)

# see the difference in the output

[  1   2 100   4   5   6   7   8   9  10  11  12]
original array : 

[[  1   2 100]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]


# 5. transpose — turning rows into columns

In [40]:
# Transpose means converting the rows to column && columns to rows

#practice array 

import numpy as np

arr = np.arange(1,7)

arr = arr.reshape(2,3)

print(arr)

print("shape of the array : ")

print(arr.shape)

[[1 2 3]
 [4 5 6]]
shape of the array : 
(2, 3)


In [44]:
# Apply the transpose 

trans = arr.T

print(trans)

print("shape of the arr after the transpose ", trans.shape)

[[1 4]
 [2 5]
 [3 6]]
shape of the arr after the transpose  (3, 2)


# 6. Understanding axis

## axis = 0 (row wise )



In [45]:
A = np.array([[1,2,3],
              [4,5,6]])

A

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# operates column wise 

s = np.sum(A,axis = 0)

s

array([5, 7, 9])

## axis = 1 across the column 

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
s = np.sum(A,axis=1)

print(s)

[ 6 15]


# 7. concatenate() — join arrays

In [62]:
# concatenate()  means merging / joining arrays 

#Rule

#axis=0 → add more rows

#axis=1 → add more columns

# creating two practice arrays 

A = np.arange(1,5).reshape(2,2)

print(A)
print()
B = np.arange(5,9).reshape(2,2)
print(B)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [60]:
# concating axis = 0  (row wise) / vertically
C = np.concatenate((A,B),axis = 0)

C

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [61]:
# concaneting axis =1 (column wise) / horizontally

D = np.concatenate((A,B),axis =1)

D

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 8. hstack and vstack (easier syntax)

In [67]:
# horizontally stack (column wise)

np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [69]:
# vertically stack ( row wise)

np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 9. Real ML Example — Creating a Feature Matrix

In [70]:
age = np.array([21, 25, 30]).reshape(-1,1)
salary = np.array([30000, 50000, 70000]).reshape(-1,1)

X = np.hstack((age, salary))

print(X)

[[   21 30000]
 [   25 50000]
 [   30 70000]]
