# ARRAY MANIPULATION

In [3]:
# SHAPE OF THE ARRAY 

import numpy as np

arr = np.arange(12) # arange starts from 0 and end before

print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
# shape of the array 

print(arr.shape)  # 12 rows , 0 cols




(12,)


## reshape()

In [9]:
# machine learning models did not understand this patter( above code)  , 

# so we change the dimesions not the data , 

#reshape function is used to change the dimensions of the data , not the change in acutual data

#syntax arr.reshape(rows,cols)


print(arr.reshape(3,4))

#Note :- this function work only

'''12 elements

3 × 4 = 12 ✅

2 × 6 = 12 ✅

4 × 3 = 12 ✅

5 × 3 = 15 ❌
'''

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'12 elements\n\n3 × 4 = 12 ✅\n\n2 × 6 = 12 ✅\n\n4 × 3 = 12 ✅\n\n5 × 3 = 15 ❌\n'

In [10]:
#example for invalid case

shape = arr.reshape(5,3)

print(shape)

ValueError: cannot reshape array of size 12 into shape (5,3)

## Automatic Dimension (-1)

In [15]:
# numpy calculate the one dimension automatically by using 9-1)

import numpy as np

matrix = np.arange(12)

print(matrix)

# reshaping 
print()
print("After reshaping")
shape = matrix.reshape(3,-1)
print()
print(shape)



[ 0  1  2  3  4  5  6  7  8  9 10 11]

After reshaping

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# working is \
# here the matrix contains the 12 elements , 
# we specify the rows (3), and columns (-1)

# the column dimnesion is automatically calculate like (12/3) = 4  (rows = 3 , total elements = 12) 

## row dimension calculation

In [16]:
shape = matrix.reshape(-1,2)

print(shape)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


## flatten() 

In [19]:
# the flatten function is used to convert any dimension array to 1 D array

import numpy as np

arr = np.arange(20)

shape = arr.reshape(5,4)

print(shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [22]:
# flatter the array

print(shape.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
# Note : - The flatten creates the copy , the original array is unchanged

print(shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## ravel()

In [25]:
# the ravel is used to convert the multidimensional array to 1d array ,
# the ravel modifies the original array 

shape.shape

(5, 4)

In [26]:
# The array(shape) contains the 5 rows and 4 columns 

print(shape.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [27]:
# The ravel function modifies the original array

print(shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
