# Statistical Operations + Axis + Real Interview Patterns


## 1. Create a sample dataset


In [2]:
# creating the practice array

import numpy as np

arr = np.array([
                 [85,92,105],
                 [88,95,102],
                 [83,98,107]
               ])

print(arr)

[[ 85  92 105]
 [ 88  95 102]
 [ 83  98 107]]


## 2. Mean()

In [3]:
# mean is the average of the all values in the arr

print(arr.mean())

# mean = sum of all / no.of all

95.0


## 3.Axis 

In [6]:
# axis = 0 (column wise)

#finding the mean column wise

col = np.mean(arr,axis=0)

# mean for entire each column
print(col)

[ 85.33333333  95.         104.66666667]


In [7]:
# axis = 1 (row wise)

# finding the mean row wise (1st row, 2 nd row, .....)

row = np.mean(arr,axis=1)

print(row)

[94. 95. 96.]


## 4.sum()

In [10]:
# sum of the entire array 

sum = np.sum(arr)

# all elements 
print(sum)

855


In [12]:
# sum of each column in the array

sum = np.sum(arr,axis = 0)

print(sum)

[256 285 314]


In [13]:
# sum of each row in the array

sum = np.sum(arr,axis =1)

print(sum)

[282 285 288]


## 5. finding the minimum and maximum

In [15]:
# finding the maximum element in the array

min = np.min(arr)

print(min)

83


In [17]:
# finding the maximum element in the array 

max = np.max(arr)

print(max)

107


In [19]:
# finding the max element for each row

max = np.max(arr,axis = 1)

print(max)

[105 102 107]


In [21]:
# finding the min element for each row

min = np.min(arr, axis = 1)

print(min)

[85 88 83]


In [24]:
# finding the min element for each column

min = np.min(arr,axis=0)

print(min)

[ 83  92 102]


In [23]:
# finding the max element for each column

max = np.max(arr,axis=0)

print(max)

[ 88  98 107]


## 6.Argmax and Argmin

In [25]:
# this two returns the index not the value

min_index = np.argmin(arr)

print(min_index)

6


In [26]:
# max value index by using argmax

max_index = np.argmax(arr)

print(max_index)

8


## 7. Standard Deviation

In [27]:
# standard deviation means , how the values far from the mean

# low sd means values are close to the mean

# high sd maens values are far from the mean

sd = np.std(arr)

print(sd)

8.192137151629671


## 8. variance

In [28]:
# variance means , how the values are spread out

var = np.var(arr)

print(var)

67.11111111111111


## 9. Median


In [30]:
# median is robust to outliers

median = np.median(arr)

print(median)

95.0


## 10. Percentiles


In [31]:
# A percentile tells us the position of a value relative to the entire dataset.

p25 = np.percentile(arr,25)

print(p25)

88.0


In [32]:
# p75

p75 = np.percentile(arr,75)

print(p75)

102.0


## keepdims()

In [33]:
# keepdims are important in the broadcasting

mean = np.mean(arr,axis=0,keepdims=True)

print(mean)

[[ 85.33333333  95.         104.66666667]]


In [34]:
marks = np.array([80, 90, 100])
weights = np.array([1, 2, 3])

np.average(marks, weights=weights)

np.float64(93.33333333333333)

np.float64(90.0)

In [ ]:
Practice Problems (Do Without Looking)

Use:

a = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

Find:

Overall mean

Column means

Row sums

Maximum of each column

Index of maximum element in each row

Standard deviation of the array

Median of the array

75th percentile

Day 6 Cheat Sheet
# Mean
np.mean(a)

# Sum
np.sum(a)

# Min / Max
np.min(a)
np.max(a)

# Index of min / max
np.argmin(a)
np.argmax(a)

# Statistics
np.std(a)
np.var(a)
np.median(a)
np.percentile(a, 25)

# Axis
np.mean(a, axis=0)  # columns
np.mean(a, axis=1)  # rows

# Keep dimensions
np.mean(a, axis=0, keepdims=True)