# PART -1 ( INDEXING )

In [1]:
# IMPORT STATEMENT

import numpy as np 

arr = np.array([1,5,12,18,24,32])

print(arr)

[ 1  5 12 18 24 32]


In [4]:
# index start from the zero and goes to n-1

print(arr[1]) # accessing the second element

5


In [6]:
#accessing the third element

print(arr[2])

12


## Negative indexing

In [7]:
# Negative indexing means accesing the elements from the last

# last element

print(arr[-1])  



32


In [9]:
# second last element 

print(arr[-2])

24


# part - 2 (sliceing)

In [12]:
#slicing means access elements for a specific range

'''  arr[start: stop : step] 

 -> arr - name of the array 
 -> start - start index (included)
 ->stop - stop index (stop index not included)
 -> step - step index (jump between elements)
 '''


print(arr[0:4:1])

''' 0 - start index included 
 4 - stop index (not included)

1 - step index (one jump )
'''

[ 1  5 12 18]


' 0 - start index included \n 4 - stop index (not included)\n\n1 - step index (one jump )\n'

In [13]:
# start - 0 , end - 5, step -2 

print(arr[0:5:2])

[ 1 12 24]


In [14]:
# start (default)

print(arr[:5])

[ 1  5 12 18 24]


In [15]:
# specigfing the start

print(arr[1:])

[ 5 12 18 24 32]


In [17]:
# Not specifing both start and end 

print(arr[::2])

[ 1 12 24]


In [18]:
# Reversing the array 

print(arr[::-1])

[32 24 18 12  5  1]


# part - 3 ( 2 D array indexing )

In [21]:
# creating the 2d matrix (rows ,cols)

# matrix is the name of the arrray 

matrix = np.array(
                   [
                       [1,2,3],
                       [4,5,6],
                       [7,8,9]
                   ]
                  )

# output

print(matrix)

# defing the shape of the matrix


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Accessing the single element

print(matrix[0,1])

# row =0 , col = 1 -> 2 

2


In [26]:
# Accessing the single element 

#accessign the 8 , row = 2, col = 2

print(matrix[2,2])

9


In [27]:
#Accessing the entire row 

print(matrix[1])

[4 5 6]


In [28]:
# Accessing the last row 

print(matrix[2])

[7 8 9]


In [29]:
#Accessing the entire column

print(matrix[:,1])

[2 5 8]


In [30]:
#Accessing the last column in the matrix

print(matrix[:,2])

[3 6 9]


In [32]:
# Accessing the first two rows

print(matrix[:2])

[[1 2 3]
 [4 5 6]]


In [33]:
# Accessing the last two columns

print(matrix[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [34]:
# Accessing the sub matrix

print(matrix[:2,1:])

[[2 3]
 [5 6]]


# part - 3 ( Fancy indexing)

In [37]:
# fancy indexing means accessing multiple vales 

import numpy as pd

a = np.array([1,2,3,4,5,6,7,8,9])

print(a[[0,2,4,5]])

[1 3 5 6]


In [38]:
# accessing even indexign

print(a[[0,2,4,6]])

[1 3 5 7]


# Part - 5 ( Boolean Indexing )

In [39]:
import numpy as np

array = np.array([1,4,7,2,5,8,3,6,9])

print(array)

[1 4 7 2 5 8 3 6 9]


In [40]:
# accessing the element greater than 3

print(array[array>3])

[4 7 5 8 6 9]


In [41]:
# Acessing the elements less than 7

print(array[array<7])

[1 4 2 5 3 6]


In [42]:
# Accessing the elements odd elements

print(array[array %2 == 0])

[4 2 8 6]


In [45]:
# Accessing the odd elements

print(array[array %2 != 0])

[1 7 5 3 9]


In [48]:
# Accessing the values between the 2 and 9

print(array[(array >2) & (array < 9)])

[4 7 5 8 3 6]


# part -6 ( Iterating through the array )

In [49]:
import numpy as np

arr = np.array([2,5,8,1,4,7,3,15])

# accessing the single element 


for value in arr:
    print(value)

2
5
8
1
4
7
3
15


In [52]:
#accessing the 2 d array 

arr = np.array([
    [1,2,3],
    [4,5,6]
])

# accesing the row wise 

for value in arr:
    print(value)

[1 2 3]
[4 5 6]


In [53]:
# Aceesing element wise

for row in arr:
    for col in row:
        print(col)

1
2
3
4
5
6


## ndeter()

In [2]:
#sometimes iterating throught the nested loops becomes inefficiednt ,

# ndeter() is a built in function , so that it is easy to traverse multi dimensional arrays

import numpy as np

arr = np.array([
                [1,2,3],
                [4,5,6]
               ])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
